---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  labels:
    app.kubernetes.io/part-of: attendees
    apps.tanzu.vmware.com/workload-type: web
  name: attendees
  namespace: dev-tap
spec:
  source:
    git:
      ref:
        branch: master
      url: https://github.com/drawsmcgraw/pcf-ers-demo
