#@data/values

#@overlay/match-child-defaults missing_ok=True

#! This file is used as a 'values' file for the manifests in
#! this directory.
---
tap:
  #! Name of additional k8s namespaces to set up for development.
  #! ref: https://docs.vmware.com/en/VMware-Tanzu-Application-Platform/1.2/tap/GUID-set-up-namespaces.html
  devNamespaces: 
    - dev-tap
    - user-01
    - user-02
    - user-03
    - user-04
    - user-05

  domains:
    learningCenter: learningcenter.tap.tanzu.corp
    knative: apps.tap.tanzu.corp
